crates/key-server/src/errors.rs
crates/key-server/src/server.rs
crates/key-server/src/valid_ptb.rs

related: https://github.com/MystenLabs/ts-sdks/pull/233

fix: add more details to InvalidPTB error

---

Cargo.lock
Cargo.toml

Set a new version, 0.3.0, for the key server.
N/A

New key server version

---

UsingSeal.md

[Docs] Update UsingSeal.md

---

Dockerfile

As in title
rerun image builds in CI

[Dockerfile] Bumping the rust version to build the image

---

UsingSeal.md

Document how to handle an `InvalidParameter` error.
N/A

Document how to handle an `InvalidParameter` error.

---

Cargo.lock
Cargo.toml

Set version 0.3.1

---

crates/key-server/src/server.rs
crates/key-server/src/tests/externals.rs
crates/key-server/src/tests/tle.rs
crates/key-server/src/valid_ptb.rs

* Log SDK version for request
* Ensure that all errors from `check_request` are reported to the metrics
Unit tests.

Log SDK version and all errors from check_request

---

UsingSeal.md
examples/frontend/package.json
examples/frontend/pnpm-lock.yaml
examples/frontend/src/AllowlistView.tsx
examples/frontend/src/App.tsx

update SessionKey usage, bump sdk

---

Cargo.lock
UsingSeal.md
crates/key-server/Cargo.toml
crates/key-server/src/tests/mod.rs
move/patterns/sources/voting.move
move/seal/sources/bf_hmac_encryption.move
move/seal/sources/key_server.move

next step: validate on client side ts-sdks in retrieveKeyServers

feat: add versioning to KeyServer

---

crates/key-server/src/server.rs

because the genkey command now only prints hex we need to be able to take in the env var as hex too
https://github.com/MystenLabs/seal/blob/main/crates/seal-cli/src/main.rs#L325

parse master key with either base64 or hex

---

crates/key-server/src/server.rs

Update the SDK version requirement.
N/A

Set SDK requirement for breaking change

---

examples/frontend/package.json
examples/frontend/pnpm-lock.yaml
examples/frontend/src/AllowlistView.tsx
examples/frontend/src/EncryptAndUpload.tsx
examples/frontend/src/SubscriptionView.tsx

[frontend] Upgrade sdk to 0.4.5

---

.github/workflows/move.yml
UsingSeal.md
examples/frontend/.eslintrc.cjs
examples/frontend/.prettierrc
examples/frontend/package.json
examples/frontend/pnpm-lock.yaml
examples/frontend/src/AllowlistView.tsx
examples/frontend/src/App.tsx
examples/frontend/src/EncryptAndUpload.tsx
examples/frontend/src/SubscriptionView.tsx
examples/frontend/src/index.html
examples/frontend/src/utils.ts

fix: Update doc and example to 0.4.6 sdk

---

Dockerfile

[Dockerfile]bump rust version for edition2024

---

examples/frontend/package.json
examples/frontend/pnpm-lock.yaml

[Seal example] upgrade to sdk 0.4.7

---

Design.md
UsingSeal.md

[Docs] fix bad links

---

UsingSeal.md
examples/frontend/package.json
examples/frontend/pnpm-lock.yaml
examples/frontend/src/AllowlistView.tsx
examples/frontend/src/EncryptAndUpload.tsx
examples/frontend/src/SubscriptionView.tsx
examples/frontend/src/networkConfig.ts

fix: use SessionKey.create

---

crates/crypto/src/ibe.rs
crates/key-server/src/server.rs
crates/seal-cli/src/main.rs

Use hex encoding for key server + refactor key derivation.

Use hex encoding + refactor key derivation

---

Cargo.lock
crates/key-server/Cargo.toml
crates/key-server/src/server.rs
crates/key-server/src/utils.rs

matches: ecb5a8ae2bf3a64d54c78a703ab50b27fa915aa0
```
2025-06-12T18:18:49.206504Z  INFO key_server: Starting server, version 0.4.2-ecb5a8ae2bf3```

chore: add git version with cargo

---

Dockerfile

```
docker build -t seal-key-server . --build-arg GIT_REVISION="$(git describe --always --abbrev=12 --dirty --exclude '*')"
```
runs successful

add build arg to docker

---

Cargo.lock
Cargo.toml

chore: Release 0.4.3

---

crates/key-server/src/tests/e2e.rs
crates/key-server/src/tests/externals.rs
crates/key-server/src/tests/mod.rs
crates/key-server/src/tests/pd.rs
crates/key-server/src/tests/server.rs
crates/key-server/src/tests/tle.rs
crates/key-server/src/tests/whitelist.rs

E2E test for permissioned key servers.
This also contains a bit of refactoring of the test framework.
...

E2E test for permissioned key servers

---

Cargo.lock
crates/key-server/Cargo.toml
crates/key-server/src/key_server_options.rs
crates/key-server/src/server.rs

A few clarifications to the master key loading + some docs.
Unit tests.

Docs + clarify

---

Cargo.lock
Cargo.toml

chore: prepare 0.4.4

---

UsingSeal.md

doc: link key servers

---

move/seal/sources/bf_hmac_encryption.move

Move: remove asserts

---

examples/move/sources/allowlist.move
move/patterns/sources/voting.move
move/seal/sources/bf_hmac_encryption.move
move/seal/sources/kdf.move
move/seal/sources/key_server.move
move/seal/sources/polynomial.move

addressed comments from: https://github.com/MystenLabs/seal/pull/199

fix: make key server owned 

---

move/patterns/sources/voting.move
move/seal/sources/bf_hmac_encryption.move
move/seal/sources/key_server.move

add store to keyserver

---

Cargo.lock
Cargo.toml

0.4.7 release

---

Cargo.lock
Cargo.toml

release 0.4.8

---

UsingSeal.md

Header for "On-chain decryption" should be lower level than "Decryption"
N/A

[docs] Fix header level

---

move/seal/sources/bf_hmac_encryption.move

Add unit test with just one key server.
...

[move] Unit test with one server

---

.github/CODEOWNERS
Pricing.md
UsingSeal.md
docs/Pricing.md
docs/UsingSeal.md
examples/frontend/package.json
examples/frontend/pnpm-lock.yaml
examples/frontend/src/AllowlistView.tsx
examples/frontend/src/EncryptAndUpload.tsx
examples/frontend/src/SubscriptionView.tsx

[docs][example] remove getAllowlistedKeyServers

---

Cargo.lock
Cargo.toml

[release] 0.4.8

---

crates/crypto/src/ibe.rs
crates/crypto/src/lib.rs

Refactor decryption + verify nonce when no pks are given.
Unit test.

Refactor and verify nonce

---

Cargo.lock
Cargo.toml

[chore] release 0.5.9

---

tests/README.md
tests/package.json
tests/pnpm-lock.yaml
tests/simple-seal-server.test.ts

[tests] update testing suite to accept api key

---

move/seal/sources/bf_hmac_encryption.move

Add missing #[test] tag to unit test.
Test the test to test the test.

[Move] Add missing #[test] tag to unit test

---

tests/simple-seal-server.test.ts

[tests] add check for header in testing suite

---

crates/key-server/src/errors.rs
crates/key-server/src/externals.rs
crates/key-server/src/mvr.rs
crates/key-server/src/server.rs

Add a debug message to all `InternalError::Failure` and log this message. The message is not shown to the user.
N/A

[server] Log debug msg for failures

---

move/seal/sources/bf_hmac_encryption.move

[move] Adding duplicate indices checks 

---

docs/UsingSeal.md

Update testnet package after upgrade.
N/A

[docs] Update testnet package in docs

---

Cargo.lock
crates/seal-cli/Cargo.toml
crates/seal-cli/src/main.rs
docs/UsingSeal.md

addressing comments: https://github.com/MystenLabs/nautilus/pull/12#discussion_r2320180616 useful for nautilus pattern

[cli] add encrypt and fetch-keys command

---

crates/key-server/key-server-config.yaml
crates/key-server/src/key_server_options.rs
crates/key-server/src/mvr.rs
crates/key-server/src/server.rs
crates/key-server/src/types.rs

[key-server]fix custom network for mvr

---

Cargo.lock

Revert "[chore] update deps"

---

.github/workflows/docs-deploy.yml

Rebuild the docs as a mkdocs site and deploy it to the Walrus site
iterate on the GH action

[workflows][docs-publish] automate doc publishing to walrus sites

---

docs/UsingSeal.md
move/seal/sources/bf_hmac_encryption.move

[docs] onchain decryption

---

.github/workflows/typescript.yml

[tests] update version

---

docs/UsingSeal.md

Minor bullet formatting issue for mkdocs
Tested locally using mkdocs serve

Minor bullet formatting issue for mkdocs

---

Cargo.lock
crates/key-server/Cargo.toml
crates/key-server/src/server.rs
crates/key-server/src/tests/server.rs
crates/key-server/src/valid_ptb.rs

[key server] more limitations

---

.github/workflows/move.yml
move/.prettierrc
move/patterns/sources/account_based.move
move/patterns/sources/key_request.move
move/patterns/sources/private_data.move
move/patterns/sources/subscription.move
move/patterns/sources/tle.move

- adds formatter CI
- adds prettierrc
- formatting

[move] move formatting + CI

---

.github/workflows/move.yml
move/.prettierrc
move/patterns/sources/account_based.move
move/patterns/sources/key_request.move
move/patterns/sources/private_data.move
move/patterns/sources/subscription.move
move/patterns/sources/tle.move
move/seal/sources/bf_hmac_encryption.move
move/seal/sources/hmac256ctr.move
move/seal/sources/kdf.move
move/seal/sources/key_server.move
move/seal/sources/polynomial.move

| Note: should go in after #324 
- order functions
- use `assert_eq!` in tests
- use receiver.syntax

[move] small code quality improvements

---

Cargo.lock
Cargo.toml
crates/key-server/Cargo.toml
crates/key-server/src/server.rs
deny.toml
docker/seal-proxy/local-test/metrics-generator/Cargo.toml

upgrade fastcrypto and prepare fastcrypto-tbls crate, https://github.com/MystenLabs/seal/pull/293/ is rebased on this

[key-server] upgrade fastcrypto and sui pointer

---

Cargo.lock
Cargo.toml
crates/crypto/src/ibe.rs
crates/crypto/src/lib.rs
crates/key-server/src/tests/e2e.rs
crates/seal-cli/src/main.rs
crates/seal-sdk/src/lib.rs

small pr for clean up. before the grpc switch pr. 

[key-server] use 0.0.8 for sui-rust-sdk
